<?php

namespace DaydreamLab\Cms\Services\Language\Admin;

use DaydreamLab\Cms\Repositories\Language\Admin\LanguageAdminRepository;
use DaydreamLab\Cms\Services\Language\LanguageService;
use DaydreamLab\JJAJ\Helpers\Helper;
use Illuminate\Support\Collection;
use Illuminate\Support\Str;

class LanguageAdminService extends LanguageService
{
    protected $type = 'LanguageAdmin';

    protected $search_keys = ['title', 'description'];

    public function __construct(LanguageAdminRepository $repo)
    {
        parent::__construct($repo);
    }


    public function getList(Collection $input)
    {
        $data = $this->findByChain(['type', 'state'], ['=', '='], [$input->get('type') ?: 'content' , 1]);

        $this->status = Str::upper(Str::snake($this->type.'GetListSuccess'));
        $this->response = $data;

        return $data;
    }

    public function search(Collection $input)
    {
        $result =  parent::search($input); // TODO: Change the autogenerated stub
        return $result;
    }
}
