<?php

namespace DaydreamLab\Cms\Services\Category\Admin;

use DaydreamLab\Cms\Repositories\Category\Admin\CategoryAdminRepository;
use DaydreamLab\Cms\Services\Category\CategoryService;
use DaydreamLab\JJAJ\Helpers\Helper;
use Illuminate\Support\Collection;

class CategoryAdminService extends CategoryService
{
    protected $type = 'CategoryAdmin';

    public function __construct(CategoryAdminRepository $repo)
    {
        parent::__construct($repo);
    }

    public function store(Collection $input)
    {
        if ($input->get('alias') == null || $input->get('alias') == ''){
            $input->forget('alias');
            $input->put('alias', now()->format('Y-m-d-H-i-s'));
        }

        if ($input->get('extension') == null || $input->get('extension') == ''){
            $input->forget('extension');
            $input->put('extension', 'category');
        }

        return parent::storeNested($input); // TODO: Change the autogenerated stub
    }
}
