<?php

namespace DaydreamLab\Cms\Services\Menu\Admin;

use DaydreamLab\Cms\Repositories\Menu\Admin\MenuAdminRepository;
use DaydreamLab\Cms\Services\Menu\MenuService;
use DaydreamLab\JJAJ\Helpers\Helper;
use DaydreamLab\JJAJ\Helpers\InputHelper;
use Illuminate\Support\Collection;
use Illuminate\Support\Fluent;
use Illuminate\Support\Str;

class MenuAdminService extends MenuService
{
    protected $type = 'MenuAdmin';

    protected $search_keys = ['title', 'description'];

    public function __construct(MenuAdminRepository $repo)
    {
        parent::__construct($repo);
    }


    public function getItem($id)
    {
        $item = parent::getItem($id);

        $this->hasPermission($item->access, $this->access_ids);

        return $this->checkLocked($item);
    }

    public function search(Collection $input)
    {
        return parent::search($input); // TODO: Change the autogenerated stub
    }
}
